#=========================================================#
#          Combat Ranking System by Cashtann              #
#                  Discord: cashtan                       #
#        Copyright Cashtann, all rights reserved          #
#=========================================================#

# If something is not working, make sure you have installed PlaceholderAPI and ProtocolLib


# Placeholders:
# {killer} - the player who killed (player who killed, is behind the murder) (nickname)
# {player} - the player who got killed (victim, died) (nickname)
# {killer_diff} - amount of points the {killer} got (unsigned int, non-negative)
# {player_diff} - amount of points the {player} lost (unsigned int, non-negative) (same as {killer_diff})
kill-message: '  #F2C6DE🗡 &fGracz #F2C6DE{killer} &7(+{killer_diff}) &fzabił gracza #F2C6DE{player} &7(-{player_diff})'

# Rating / ranking / score / points is a INTEGER value (no decimal points, it is being rounded down (truncated))
# Initial combat rating (score) when a player joins the server for the first time
initial-combat-rating: 1000

# Combat score modifier when player kills or gets killed in percent (0.0 means 0%, 1.0 means 100%)
# Adding % of killed player rating to killer's rating and removing (%) from the killed player
# example with 5%: PlayerA (rating of 1000) killed PlayerB (rating of 500),
# PlayerA gains 25 score points (5% of 500) and PlayerB loses 25 score points (5% of 500)
# Result: PlayerA - 1025, PlayerB - 475
combat-score-modifier: 0.05

# Chat settings
chat:
  # Rating related
  rating:
    # Chat rating prefix (when player sends message)
    # It is shown before message, player display name and rank (very start of the message)
    # Use placeholder {rating} to set the rating value
    enabled: true
    # Remember, if you want to have space between rating and nickname/rank, add space at the end
    # like in the default configuration
    prefix: '&7[{rating}] '
